name: build our image

"on":
  push:
    branches: ["main", "arm-container"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build image
        if: github.ref == 'refs/heads/main'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build \
            --push \
            --tag damacus/cert-manager-webhook-dnsimple:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
      - name: Build unstable image
        if: github.ref != 'refs/heads/main'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build \
            --push \
            --tag damacus/cert-manager-webhook-dnsimple:unstable \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
